-- CREATE A MIGRATION ENTRY
INSERT INTO `DB_MIGRATIONS` (`MIGRATION`) VALUES ('20190127_cnr_gang_ranks');

-- BEGIN
CREATE TABLE `USER_GANG_RANKS` (
`ID` int(11) PRIMARY KEY AUTO_INCREMENT NOT NULL,
`USER_ID` int(11) UNIQUE KEY DEFAULT NULL,
`GANG_RANK_ID` int(11) DEFAULT NULL,
`RESPECT` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `GANG_RANKS` (
`ID` int(11) PRIMARY KEY AUTO_INCREMENT NOT NULL,
`GANG_ID` int(11) NOT NULL,
`RANK_NAME` varchar(32) DEFAULT NULL,
`COLOR` int(11) DEFAULT NULL,
`REQUIRE` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;