-- CREATE A MIGRATION ENTRY
INSERT INTO `DB_MIGRATIONS` (`MIGRATION`) VALUES ('20190101_cnr_remove_xp_autosave');

-- BEGIN

-- -- REMOVE REDUNDANT COLUMN XP IN USERS
ALTER TABLE `USERS` DROP `XP`;

-- -- REMOVE AUTO SAVE SETTING
DELETE FROM `SETTINGS` WHERE SETTING_ID = 5;

-- -- REPLACE AUTO SAVE SETTING WITH CHAT ID SETTING
UPDATE SETTINGS SET SETTING_ID = 5 WHERE SETTING_ID = 13;

-- -- REMOVE MEGABAN TABLE ... REDUNDANT
DROP TABLE `MEGABAN`;