/*
 * Irresistible Gaming 2018
 * Developed by Lorenc Pekaj
 * Module: main.inc
 * Purpose: centralize includes
 */

// default
#include < irresistible\settings > // keep #1
#include < irresistible\security >
#include < irresistible\helpers >
#include < irresistible\floodcontrol >
#include < irresistible\mailer >
#include < irresistible\colors >
#include < irresistible\attachments >
#include < irresistible\lookup >
#include < irresistible\servervars >
// #include <irresistible\analytics >

// gta related variables
#include < irresistible\gta\map >
#include < irresistible\gta\vehicles >
#include < irresistible\gta\weapon_data >

// cnr configuration
#include < irresistible\cnr\cities >
#include < irresistible\cnr\dialog_ids >
#include < irresistible\cnr\vip >

// features
#include < irresistible\features\fps >
#include < irresistible\features\radio >
#include < irresistible\features\cash_cards >
#include < irresistible\features\furniture >
// #include < irresistible\features\vote >

// gangs and facilities
#include < irresistible\features\gangs\gangs >
#include < irresistible\features\gangs\facilities >
#include < irresistible\features\gangs\turfs >

// visage casino
#include < irresistible\features\visage\roulette >
#include < irresistible\features\visage\blackjack >
#include < irresistible\features\visage\poker >
#include < irresistible\features\visage\fireworks >
#include < irresistible\features\visage\casino >
#include < irresistible\features\visage\apartments >
#include < irresistible\features\visage\boxing >

// static cnr features
#include < irresistible\cnr\static\actors >
#include < irresistible\cnr\static\server_vehicles >
#include < irresistible\cnr\static\removed_buildings >
#include < irresistible\cnr\static\server_objects >
#include < irresistible\cnr\static\player_objects >
