/*
 * Irresistible Gaming 2018
 * Developed by Lorenc Pekaj
 * Module: main.inc
 * Purpose: centralize includes
 */

// default
#include < irresistible\settings > // keep #1
#include < irresistible\security >
#include < irresistible\helpers >
#include < irresistible\floodcontrol >
#include < irresistible\mailer >
#include < irresistible\colours >
#include < irresistible\attachments >
#include < irresistible\lookup >
// #include <irresistible\analytics >

// gta related variables
#include < irresistible\gta\map >
#include < irresistible\gta\vehicles >
#include < irresistible\gta\weapon_data >

// features
#include < irresistible\features\fps >
#include < irresistible\features\radio >

// visage casino
#include < irresistible\features\visage\blackjack >
#include < irresistible\features\visage\poker >
// #include < irresistible\features\visage\fireworks >
#include < irresistible\features\visage\apartments >
#include < irresistible\features\visage\static_casino >

// static
#include < irresistible\static_cnr\actors >
#include < irresistible\static_cnr\server_vehicles >
#include < irresistible\static_cnr\removed_buildings >
#include < irresistible\static_cnr\removed_furniture >
#include < irresistible\static_cnr\server_objects >
#include < irresistible\static_cnr\player_objects >
